Areas/admin/Models/Entities/Customers/BaseEntity.cs
namespace Task_16.Areas.admin.Models.Entities.Customers
{
    public class BaseEntity
    {
        public Guid Id { get; set; }
    }
}

Areas/admin/Models/Entities/Statistics.cs
using System.ComponentModel.DataAnnotations;
using Task_16.Areas.admin.Models.Entities.Customers;

namespace Task_16.Areas.admin.Models.Entities
{
    public class Statistics : BaseEntity
    {
        [Required(ErrorMessage = "Zorunlu alan ")]
        public decimal Statistic { get; set; }
        [Required(ErrorMessage = "Zorunlu alan ")]
        public string? StatisticsName { get; set; }
        [Required(ErrorMessage = "Zorunlu alan ")]
        public float StatisticsPercentage { get; set; }
        [Required(ErrorMessage = "Zorunlu alan ")]
   
        public  DateTime StatisticsTime {get; set; }
        [Required(ErrorMessage = "Zorunlu alan ")]
        public string? StatisticsDuration { get; set; }
        [Required(ErrorMessage = "Zorunlu alan ")]
        public string? StatisticsVisit { get; set; }
        [Required(ErrorMessage = "Zorunlu alan ")]
        public string? StatisticsVisits { get; set; }
        [Required(ErrorMessage = "Zorunlu alan ")]
        public float StatisticsPercentages { get; set; }
        [Required(ErrorMessage = "Zorunlu alan ")]
        public float StatisticsPercent { get; set; }


    }
}

Areas/admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Task_16.Areas.admin.Models.Entities;
using Task_16.Context;


namespace Task_16.Areas.admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {

        readonly private Task16DbContext _context;
        public DashboardController(Task16DbContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index()
        {

            var statistic = await _context.Statistics.Select(s =>
             new Statistics()
             {
                 Statistic = s.Statistic,
                 StatisticsName = s.StatisticsName,
                 StatisticsPercentage = s.StatisticsPercentage,
                 StatisticsDuration=s.StatisticsDuration,
                 StatisticsVisit=s.StatisticsVisit,
                 StatisticsVisits=s.StatisticsVisits,
                 StatisticsTime=s.StatisticsTime,
                 StatisticsPercent=s.StatisticsPercent,
                 StatisticsPercentages=s.StatisticsPercentages,

             }).ToListAsync();

            return View(statistic);
        }
    }
}

Areas/admin/Controllers/FormsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Task_16.Areas.admin.Data.Dto.Staticstic;
using Task_16.Areas.admin.Models.Entities;
using Task_16.Context;

namespace Task_16.Areas.admin.Controllers
{
    [Area("Admin")]
    public class FormsController : Controller
    {
        readonly private Task16DbContext _context;
        public FormsController(Task16DbContext context)
        {
            _context = context;
        }
        [HttpGet]
        public async Task<IActionResult> CreateForm()
        {

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> CreateForm(CreateStatisticDto model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("CreateForm");
            }
            Statistics statistics = new Statistics()
            {
                Statistic = model.Statistic,
                StatisticsName = model.StatisticsName,
                StatisticsPercentage = model.StatisticsPercentage,
                StatisticsDuration = model.StatisticsDuration,
                StatisticsPercent = model.StatisticsPercent,
                StatisticsPercentages = model.StatisticsPercentages,
                StatisticsTime = model.StatisticsTime,
                StatisticsVisit = model.StatisticsVisit,
                StatisticsVisits = model.StatisticsVisits
            };


            await _context.Statistics.AddAsync(statistics);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Dashboard");


        }

        [HttpGet]
        public async Task<IActionResult> UpdateForm(string id)
        {
            var statistics = await _context.Statistics.FindAsync(Guid.Parse(id));

            if (statistics == null)
            {
                return NotFound();
            }

            var updateStatisticDto = new UpdateStatisticDto
            {
                Id = statistics.Id.ToString(),
                Statistic = statistics.Statistic,
                StatisticsName = statistics.StatisticsName,
                StatisticsPercentage = statistics.StatisticsPercentage,
                StatisticsDuration = statistics.StatisticsDuration,
                StatisticsPercent = statistics.StatisticsPercent,
                StatisticsPercentages = statistics.StatisticsPercentages,
                StatisticsTime = statistics.StatisticsTime,
                StatisticsVisit = statistics.StatisticsVisit,
                StatisticsVisits = statistics.StatisticsVisits
            };

            return View(updateStatisticDto);
        }



        [HttpPost]
        public async Task<IActionResult> UpdateForm(UpdateStatisticDto model)
        {

            Statistics?  statistics = await _context.Statistics.FindAsync( Guid.Parse(model.Id));
            if(!ModelState.IsValid)
            {
                return View(model);
            }
            if(statistics == null)
            {
                return NotFound();
            }
            else
            {
               
                statistics.Statistic = model.Statistic;
                statistics.StatisticsName = model.StatisticsName;
                statistics.StatisticsPercentage = model.StatisticsPercentage;
                statistics.StatisticsDuration = model.StatisticsDuration;
                statistics.StatisticsPercent = model.StatisticsPercent;
                statistics.StatisticsTime = model.StatisticsTime;
                statistics.StatisticsVisit = model.StatisticsVisit;
                statistics.StatisticsVisits = model.StatisticsVisits;
                statistics.StatisticsTime = model.StatisticsTime;


                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Tables");
            }

           
        
           


        }

        [HttpPost]
        public async Task <IActionResult> DeleteForm(string id)
        {
            var  statistics = await _context.Statistics.SingleOrDefaultAsync(st=>st.Id== Guid.Parse(id))  ;

            if (statistics == null)
            {
                return NotFound();
            }
             _context.Statistics.Remove(statistics);  
              await _context.SaveChangesAsync() ;
           
             
             return RedirectToAction("Index", "Tables");
        }
    }


}

Areas/admin/Controllers/TablesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Task_16.Areas.admin.Models.Entities;
using Task_16.Context;

namespace Task_16.Areas.admin.Controllers
{
    [Area("Admin")]
    public class TablesController : Controller
    {
        readonly private Task16DbContext _context;
        public TablesController(Task16DbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {

            List<Statistics> statistics = await _context.Statistics.ToListAsync();
            return View(statistics);
        }
 
        public async Task<IActionResult> Details(string id)
        {
            var statistics = await _context.Statistics.FindAsync(Guid.Parse(id));
            if (statistics == null)
            {
                return NotFound();
            }
            return View(statistics);
        }
    }
}

Areas/admin/Views/Forms/CreateForm.cshtml
@using Task_16.Areas.admin.Data.Dto.Staticstic;
@model   CreateStatisticDto


<div class="card">
    <div class="card-body">
        <div class="card-title"> Form</div>
        <hr>
        <form asp-area="Admin" asp-controller="Forms" asp-action="CreateForm" method="post">
            <div class="form-group">
                <label asp-for="@Model.Statistic"></label>
                <input asp-for="@Model.Statistic" class="form-control" placeholder="Enter Statistic" />
                <span asp-validation-for="@Model.Statistic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.StatisticsName"></label>
                <input asp-for="@Model.StatisticsName" class="form-control" placeholder="Enter Statistics Name">
                <span asp-validation-for="@Model.StatisticsName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.StatisticsVisit"></label>
                <input asp-for="@Model.StatisticsVisit" class="form-control" placeholder="Enter the visit">
                <span asp-validation-for="@Model.StatisticsVisit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.StatisticsVisits"></label>
                <input asp-for="@Model.StatisticsVisits" class="form-control" placeholder="Enter the visit">
                <span asp-validation-for="@Model.StatisticsVisits" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.StatisticsDuration"></label>
                <input asp-for="@Model.StatisticsDuration" class="form-control" placeholder="Enter the visit">
                <span asp-validation-for="@Model.StatisticsDuration" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <label asp-for="@Model.StatisticsTime">Time</label>
                <input asp-for="@Model.StatisticsTime" type="time" class="form-control" placeholder="Enter the visit">
                <span asp-validation-for="@Model.StatisticsTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.StatisticsPercent"></label>
                <input asp-for="@Model.StatisticsPercent" class="form-control" placeholder="Enter the visit">
                <span asp-validation-for="@Model.StatisticsPercent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.StatisticsPercentage"></label>
                <input asp-for="@Model.StatisticsPercentage" class="form-control" placeholder="Enter the visit">
                <span asp-validation-for="@Model.StatisticsPercentage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.StatisticsPercentages"></label>
                <input asp-for="@Model.StatisticsPercentages" class="form-control" placeholder="Enter the visit">
                <span asp-validation-for="@Model.StatisticsPercentages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-light px-5"><i class="icon-lock"></i> Create</button>
         </div>
        </form>
    </div>
</div>

Areas/admin/Views/Forms/UpdateForm.cshtml
@using Task_16.Areas.admin.Data.Dto.Staticstic;
@model UpdateStatisticDto



<div class="card">
    <div class="card-body">
        <div class="card-title"> Form</div>
        <hr>
        <form asp-area="Admin" asp-controller="Forms" asp-action="CreateForm" method="post">
            <div class="form-group">
                <label asp-for="@Model.Statistic"></label>
                <input asp-for="@Model.Statistic" class="form-control" placeholder="Enter Statistic" />
                <span asp-validation-for="@Model.Statistic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.StatisticsName"></label>
                <input asp-for="@Model.StatisticsName" class="form-control" placeholder="Enter Statistics Name">
                <span asp-validation-for="@Model.StatisticsName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.StatisticsVisit"></label>
                <input asp-for="@Model.StatisticsVisit" class="form-control" placeholder="Enter the visit">
                <span asp-validation-for="@Model.StatisticsVisit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.StatisticsVisits"></label>
                <input asp-for="@Model.StatisticsVisits" class="form-control" placeholder="Enter the visit">
                <span asp-validation-for="@Model.StatisticsVisits" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.StatisticsDuration"></label>
                <input asp-for="@Model.StatisticsDuration" class="form-control" placeholder="Enter the visit">
                <span asp-validation-for="@Model.StatisticsDuration" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.StatisticsTime">Time</label>
                <input asp-for="@Model.StatisticsTime" type="time" class="form-control" placeholder="Enter the visit">
                <span asp-validation-for="@Model.StatisticsTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.StatisticsPercent"></label>
                <input asp-for="@Model.StatisticsPercent" class="form-control" placeholder="Enter the visit">
                <span asp-validation-for="@Model.StatisticsPercent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.StatisticsPercentage"></label>
                <input asp-for="@Model.StatisticsPercentage" class="form-control" placeholder="Enter the visit">
                <span asp-validation-for="@Model.StatisticsPercentage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.StatisticsPercentages"></label>
                <input asp-for="@Model.StatisticsPercentages" class="form-control" placeholder="Enter the visit">
                <span asp-validation-for="@Model.StatisticsPercentages" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-light px-5"><i class="icon-lock"></i> Create</button>
            </div>
        </form>
    </div>
</div>

Areas/admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashtreme Admin - Free Dashboard for Bootstrap 4 by Codervent</title>
    <!-- loader-->
    <!--favicon-->
    <link rel="icon" href="~/assets/images/favicon.ico" type="image/x-icon">
    <!-- Vector CSS -->
    <link href="~/assets/plugins/vectormap/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <!-- simplebar CSS-->
    <link href="~/assets/plugins/simplebar/css/simplebar.css" rel="stylesheet" />
    <!-- Bootstrap core CSS-->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <!-- animate CSS-->
    <link href="~/assets/css/animate.css" rel="stylesheet" type="text/css" />
    <!-- Icons CSS-->
    <link href="~/assets/css/icons.css" rel="stylesheet" type="text/css" />
    <!-- Sidebar CSS-->
    <link href="~/assets/css/sidebar-menu.css" rel="stylesheet" />
    <!-- Custom Style-->
    <link href="~/assets/css/app-style.css" rel="stylesheet" />

</head>

<body class="bg-theme bg-theme1">

    <!-- Start wrapper-->
    <div id="wrapper">

        <!--Start sidebar-wrapper-->
        <div id="sidebar-wrapper" data-simplebar="" data-simplebar-auto-hide="true">
            <div class="brand-logo">
                <a href="index.html">
                    <img src="~/assets/images/logo-icon.png" class="logo-icon" alt="logo icon">
                    <h5 class="logo-text">Dashtreme Admin</h5>
                </a>
            </div>
            <ul class="sidebar-menu do-nicescrol">
                <li class="sidebar-header">MAIN NAVIGATION</li>
                <li>
                    <a href="/">
                        <i class="zmdi zmdi-view-dashboard"></i> <span>Dashboard</span>
                    </a>
                </li>

                <li>
                    <a href="icons.html">
                        <i class="zmdi zmdi-invert-colors"></i> <span>UI Icons</span>
                    </a>
                </li>

                <li>
                    <a href="form">
                        <i class="zmdi zmdi-format-list-bulleted"></i> <span>Forms</span>
                    </a>
                </li>

                <li>
                    <a href="tables">
                        <i class="zmdi zmdi-grid"></i> <span>Tables</span>
                    </a>
                </li>

                <li>
                    <a href="calendar.html">
                        <i class="zmdi zmdi-calendar-check"></i> <span>Calendar</span>
                        <small class="badge float-right badge-light">New</small>
                    </a>
                </li>

                <li>
                    <a href="profile.html">
                        <i class="zmdi zmdi-face"></i> <span>Profile</span>
                    </a>
                </li>

                <li>
                    <a href="login.html" target="_blank">
                        <i class="zmdi zmdi-lock"></i> <span>Login</span>
                    </a>
                </li>

                <li>
                    <a href="register.html" target="_blank">
                        <i class="zmdi zmdi-account-circle"></i> <span>Registration</span>
                    </a>
                </li>

                <li class="sidebar-header">LABELS</li>
                <li><a href="javaScript:void();"><i class="zmdi zmdi-coffee text-danger"></i> <span>Important</span></a></li>
                <li><a href="javaScript:void();"><i class="zmdi zmdi-chart-donut text-success"></i> <span>Warning</span></a></li>
                <li><a href="javaScript:void();"><i class="zmdi zmdi-share text-info"></i> <span>Information</span></a></li>

            </ul>

        </div>
        <!--End sidebar-wrapper-->
        <!--Start topbar header-->
        <header class="topbar-nav">
            <nav class="navbar navbar-expand fixed-top">
                <ul class="navbar-nav mr-auto align-items-center">
                    <li class="nav-item">
                        <a class="nav-link toggle-menu" href="javascript:void();">
                            <i class="icon-menu menu-icon"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <form class="search-bar">
                            <input type="text" class="form-control" placeholder="Enter keywords">
                            <a href="javascript:void();"><i class="icon-magnifier"></i></a>
                        </form>
                    </li>
                </ul>

                <ul class="navbar-nav align-items-center right-nav-link">
                    <li class="nav-item dropdown-lg">
                        <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown" href="javascript:void();">
                            <i class="fa fa-envelope-open-o"></i>
                        </a>
                    </li>
                    <li class="nav-item dropdown-lg">
                        <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown" href="javascript:void();">
                            <i class="fa fa-bell-o"></i>
                        </a>
                    </li>
                    <li class="nav-item language">
                        <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown" href="javascript:void();"><i class="fa fa-flag"></i></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li class="dropdown-item"> <i class="flag-icon flag-icon-gb mr-2"></i> English</li>
                            <li class="dropdown-item"> <i class="flag-icon flag-icon-fr mr-2"></i> French</li>
                            <li class="dropdown-item"> <i class="flag-icon flag-icon-cn mr-2"></i> Chinese</li>
                            <li class="dropdown-item"> <i class="flag-icon flag-icon-de mr-2"></i> German</li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" data-toggle="dropdown" href="#">
                            <span class="user-profile"><img src="https://via.placeholder.com/110x110" class="img-circle" alt="user avatar"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li class="dropdown-item user-details">
                                <a href="javaScript:void();">
                                    <div class="media">
                                        <div class="avatar"><img class="align-self-start mr-3" src="https://via.placeholder.com/110x110" alt="user avatar"></div>
                                        <div class="media-body">
                                            <h6 class="mt-2 user-title">Sarajhon Mccoy</h6>
                                            <p class="user-subtitle">mccoy@example.com</p>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><i class="icon-envelope mr-2"></i> Inbox</li>
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><i class="icon-wallet mr-2"></i> Account</li>
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><i class="icon-settings mr-2"></i> Setting</li>
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><i class="icon-power mr-2"></i> Logout</li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </header>
        <!--End topbar header-->

        <div class="clearfix"></div>
        <div class="content-wrapper">
            @RenderBody()
            </div>
        
        <!--End content-wrapper-->
        <!--Start Back To Top Button-->
        <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
        <!--End Back To Top Button-->
        <!--Start footer-->
        <footer class="footer">
            <div class="container">
                <div class="text-center">
                    Copyright © 2018 Dashtreme Admin
                </div>
            </div>
        </footer>
        <!--End footer-->
        <!--start color switcher-->
        <div class="right-sidebar">
            <div class="switcher-icon">
                <i class="zmdi zmdi-settings zmdi-hc-spin"></i>
            </div>
            <div class="right-sidebar-content">

                <p class="mb-0">Gaussion Texture</p>
                <hr>

                <ul class="switcher">
                    <li id="theme1"></li>
                    <li id="theme2"></li>
                    <li id="theme3"></li>
                    <li id="theme4"></li>
                    <li id="theme5"></li>
                    <li id="theme6"></li>
                </ul>

                <p class="mb-0">Gradient Background</p>
                <hr>

                <ul class="switcher">
                    <li id="theme7"></li>
                    <li id="theme8"></li>
                    <li id="theme9"></li>
                    <li id="theme10"></li>
                    <li id="theme11"></li>
                    <li id="theme12"></li>
                    <li id="theme13"></li>
                    <li id="theme14"></li>
                    <li id="theme15"></li>
                </ul>

            </div>
        </div>
        <!--end color switcher-->

    </div><!--End wrapper-->
    <!-- Bootstrap core JavaScript-->
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>

    <!-- simplebar js -->
    <script src="~/assets/plugins/simplebar/js/simplebar.js"></script>
    <!-- sidebar-menu js -->
    <script src="~/assets/js/sidebar-menu.js"></script>
    <!-- loader scripts -->
    @* <script src="~/assets/js/jquery.loading-indicator.js"></script> *@
    <!-- Custom scripts -->
    <script src="~/assets/js/app-script.js"></script>
    <!-- Chart js -->

    <script src="~/assets/plugins/Chart.js/Chart.min.js"></script>

    <!-- Index js -->
    <script src="~/assets/js/index.js"></script>


</body>
</html>

Areas/admin/Views/Tables/Details.cshtml
@model Statistics 


<div class="card">
      <h1>@Model.StatisticsName</h1>
    <div class="card-body"></div>
</div>

Areas/admin/Views/Tables/Index.cshtml
@model List<Statistics>
<div class="row mt-3">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Basic Table</h5>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Stastics</th>
                                <th scope="col">Name </th>
                                <th scope="col">Duration</th>
                                <th scope="col">Edit</th>
                                
                                <th scope="col">Details</th>
                                <th scope="col">Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                @if (Model.Count != 0){
                                    @foreach(var data  in Model )
                                    {
                                        <tr>
                                            <th scope="row">1</th>
                                            <td>@data.Statistic</td>
                                            <td>@data.StatisticsName</td>
                                            <td>@data.StatisticsDuration</td>
                                            <td> <a href="update/@data.Id">Edit</a></td>
                                            <td> <a href="details/@data.Id">Details</a></td>
                                            <td>
                                             <form asp-controller="Forms"  asp-action="DeleteForm" asp-area="Admin" asp-route-id="@data.Id" method="post">
                                           
                                            <button type="submit"   style="color:#fff !important; background:none; border:none ; outline:none   ">Delete</button>
                                                </form>
                                            </td>
                                          
                                            

                                        </tr>

                                    }
                                }else{
                                     <tr>
                                     <th>Not Found</th>
                                     </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>